## Web Scraping

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
base_url='https://www.propertypro.ng/property-for-rent/in/lagos?search=&auto=&type=&bedroom=&max_price='
headers={'User Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'}

In [5]:
r=requests.get(base_url, headers=headers)

In [6]:
r.status_code

200

In [7]:
soup=BeautifulSoup(r.text,'html.parser')

In [8]:
print(soup.prettify())


              <a href="/property-for-rent/in/rivers/port-harcourt">
               House for rent in Port Harcourt
              </a>
             </li>
             <li>
              <a href="/property-for-rent/in/kaduna">
               Houses for rent in Kaduna
              </a>
             </li>
            </ul>
           </div>
           <div class="col-lg-4 col-md-4 col-sm-4">
            <ul>
             <li>
              <a href="/property-for-short-let/in/lagos">
               Short let in Lagos
              </a>
             </li>
             <li>
              <a href="/property-for-short-let/in/lagos/ikeja">
               Short let in Ikeja
              </a>
             </li>
             <li>
              <a href="/property-for-short-let/in/lagos/lekki">
               Short let in Lekki
              </a>
             </li>
             <li>
              <a href="/property-for-rent/commercial-property/office-space/in/lagos">
               Office space fo

In [9]:
print(soup.title.get_text())

Property & Houses for rent  in Lagos   (27,332 listings) | PropertyPro.ng


In [10]:
titles=soup.select('.pro-main-cont>a>h2')
len(titles)

20

In [11]:
titles_list=[]
for title in titles:
    titles_list.append(title.get_text())
titles_list[0]

'3 BEDROOM FLAT / APARTMENT FOR RENT BANANA ISLAND IKOYI LAGOS'

In [12]:
locations=soup.select('.pro-location')
len(locations)

20

In [13]:
locations_list=[]
for location in locations[0:21]:
    locations_list.append(location.get_text())
len(locations_list)
locations_list[1]

'  ikate lekki lagos'

In [89]:
prices=soup.select('.prop-price>span')
len(prices)

40

In [90]:
prices_list=[]
for i, price in enumerate(prices):
    if i % 2!= 0:
        prices_list.append(price.get_text())
prices_list[1]

'20,000,000'

In [91]:
aux=soup.select('.prop-features>span>span')
len(aux)

66

In [92]:
aux_list=[]
for aux in aux:
    aux_list.append(aux.get_text())

print(aux_list)
len(aux_list)

['1 bed', '1 bath', '1 toilet', ' bed', ' bath', '10 toilet', '2 bed', '2 bath', '3 toilet', '2 bed', '2 bath', '3 toilet', '4 bed', '4 bath', '4 toilet', '5 bed', '5 bath', '6 toilet', '2 bed', '2 bath', '3 toilet', '3 bed', '4 bath', '4 toilet', '3 bed', '0 bath', '0 toilet', '3 bed', '3 bath', '4 toilet', '4 bed', '4 bath', '5 toilet', '4 bed', '4 bath', '5 toilet', '4 bed', '3 bath', '4 toilet', '4 bed', '3 bath', '4 toilet', '2 bed', '2 bath', '3 toilet', '5 bed', '6 bath', '7 toilet', '4 bed', '4 bath', '5 toilet', '3 bed', '3 bath', '4 toilet', '3 bed', '3 bath', '4 toilet', '4 bed', '4 bath', '5 toilet', '3 bed', '3 bath', '4 toilet', '3 bed', '3 bath', '4 toilet']


66

In [93]:
lists=np.arange(0,20).tolist()
a=[]
i=0
for num in lists:
    a.append(i)
    i+=3
a

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57]

In [97]:
bed=[aux_list[i] for i in (a)]
len(bed)

20

In [96]:
list=np.arange(0,20).tolist()
b=[]
i=1
for num in list:
    b.append(i)
    i+=3
b

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58]

In [98]:
bath=[aux_list[i] for i in (b)]
len(bath)

20

In [99]:
list=np.arange(0,20).tolist()
c=[]
i=2
for num in list:
    c.append(i)
    i+=3
c

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59]

In [100]:
toilet=[aux_list[i] for i in (c)]
len(toilet)

20

In [107]:
def scrape_page(url):
      return titles_list, prices_list,locations_list, beds,bath,toilet

In [105]:
urls=[base_url]
for i in range(1,676):
    url= base_url+'?page=' + str(i)
    urls.append(url)
urls[675]

'https://www.propertypro.ng/property-for-rent/in/lagos?search=&auto=&type=&bedroom=&max_price=?page=675'

In [108]:
master_titles,master_prices,master_locations,master_bed,master_bath,master_toilet=[],[],[],[],[],[]
for url in urls:
    titles_list, prices_list, locations_list , bed,bath,toilet= scrape_page(url)
    master_titles += titles_list
    master_prices += prices_list
    master_locations += locations_list
    master_bed += bed
    master_bath += bath
    master_toilet += toilet
len(master_toilet)
len(master_prices)
len(master_locations)
len(master_titles)
len(master_bed)
len(master_bath)

13520

In [109]:
property=pd.DataFrame({'title':master_titles, 'price':master_prices, 'location':master_locations,'bed':master_bed, 'bath':master_bath,'toilet':master_toilet})

In [110]:
property.to_csv('Lagos_property.csv')

In [133]:
prop=pd.read_csv('Lagos_property.csv')

In [134]:
prop.head()

title     price  \
0  1 BEDROOM MINI FLAT MINI FLAT FLAT / APARTMENT...    200000   
1  OFFICE SPACE COMMERCIAL PROPERTY FOR RENT 1, S...  20000000   
2  2 BEDROOM BLOCKS OF FLATS HOUSE FOR RENT OFF I...    300000   
3  2 BEDROOM FLAT / APARTMENT FOR RENT OLD IKOYI ...   8000000   
4  4 BEDROOM OFFICE SPACE COMMERCIAL PROPERTY FOR...   3800000   

                                            location  bed  bath  toilet  
0                 meiran abule egba abule egba lagos    1     1       1  
1    1, sylvia crescent, anthony village, ilupeju...    0     0       1  
2    off ikola road command alagbado abule egba l...    2     2       3  
3                              old ikoyi ikoyi lagos    2     2       3  
4                           toyin street ikeja lagos    4     4       4

## LinearRegression analysis 

In [135]:
prop.describe()

price           bed          bath       toilet
count  1.352000e+04  13520.000000  13520.000000  13520.00000
mean   6.890000e+06      3.100000      2.950000      3.75000
std    4.939201e+06      1.260999      1.499222      1.63942
min    2.000000e+05      0.000000      0.000000      0.00000
25%    4.000000e+06      2.000000      2.000000      3.00000
50%    5.000000e+06      3.000000      3.000000      4.00000
75%    9.250000e+06      4.000000      4.000000      5.00000
max    2.000000e+07      5.000000      6.000000      7.00000

In [136]:
prop.drop(['title','location'],inplace=True,axis=1)

In [137]:
prop.corr()

price       bed      bath    toilet
price   1.000000 -0.238284 -0.395102 -0.382557
bed    -0.238284  1.000000  0.849037  0.810293
bath   -0.395102  0.849037  1.000000  0.971447
toilet -0.382557  0.810293  0.971447  1.000000

In [138]:
x=prop.drop('price', axis=1)
y=prop['price']

In [139]:
x=x.to_numpy()
y=y.to_numpy()

In [140]:
reg=LinearRegression()

In [141]:
reg.fit(x,y)

LinearRegression()

In [142]:
w=reg.coef_
w

array([ 1386675.62235005, -2655694.55522435,   342433.14722302])

In [143]:
b=reg.intercept_
b

9141480.206540342

In [144]:
y_=reg.predict(x)
y_

array([8214894.42088907, 9483913.35376336, 7630741.78246081, ...,
       6704155.99680953, 6704155.99680953, 5777570.21115826])

In [145]:
reg.score(x,y)

0.19065098750991538

## To predict price

In [152]:
reg.predict(x[0].reshape(-1,3))

array([8214894.42088907])

In [153]:
y[2]

300000